version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  store:
    steps:
      - store_artifacts:
          path: /home/circleci/project/target

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - store