version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  docker:
    - image: python:3.6.3-jessie
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD
  store:
    steps:
      - store_artifacts:
          path: /home/circleci/project/target

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - store